name: Self Hosted Runner Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Check Runner
        run: |
          echo "GitHub self-hosted runner is working"
          echo "Hostname:"
          hostname
          echo "User:"
          whoami
          echo "Docker version:"
          docker --version
          echo "Docker containers:"
          docker ps
